# Generated by Django 2.2.6 on 2019-10-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulecnik', '0002_auto_20191023_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
