# Generated by Django 2.2.6 on 2019-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulecnik', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='Kulecnik.Player'),
        ),
    ]
