# Generated by Django 2.2.6 on 2019-10-23 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kulecnik', '0005_auto_20191023_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_t',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='game_t',
            name='player_2',
        ),
        migrations.AddField(
            model_name='game_t',
            name='team_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='Kulecnik.Team'),
        ),
        migrations.AddField(
            model_name='game_t',
            name='team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='Kulecnik.Team'),
        ),
        migrations.AlterField(
            model_name='game_s',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game_s',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game_t',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_t', to='Kulecnik.Team'),
        ),
    ]
