# Generated by Django 2.2.5 on 2019-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulecnik', '0006_auto_20191023_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_s',
            name='place',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
